site_name: Statute Patterns Docs
site_description: Statute Titles for LawSQL.com
repo_url: https://github.com/justmars/statute-patterns
theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  version:
    provider: mike
nav:
  - index.md
  - api-extract.md
  - api-title.md
  - Rule:
    - api-rule.md
    - api-rule-serial.md
    - api-rule-named.md
    - api-rule-base.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_category_heading: true
            show_source: true
            heading_level: 3
  - search:
      lang: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
